[package]
org = "xlibb"
name = "pubsub"
version = "@toml.version@"
authors = ["xlibb"]
keywords = ["pubsub"]
repository = "https://github.com/xlibb/module-pubsub"
license = ["Apache-2.0"]
distribution = "2201.10.0-20241025-103700-5c9e6a27"
icon = "icon.png"

[[platform.java21.dependency]]
path = "../native/build/libs/pubsub-native-@project.version@.jar"
