[package]
org = "xlibb"
name = "pubsub"
version = "1.5.0"
authors = ["xlibb"]
keywords = ["pubsub"]
repository = "https://github.com/xlibb/module-pubsub"
license = ["Apache-2.0"]
distribution = "2201.11.0"
icon = "icon.png"

[[platform.java21.dependency]]
path = "../native/build/libs/pubsub-native-1.5.0.jar"
